### ISSUE TITLE
We are in space and there is no roof

### ISSUE THREAD

**Issue by gdinit** [fallahn/LunarMooner#10]
Enhancement request:
When you fly your lander higher than top of the screen you bounce back from an imaginary roof. 
There is no roof or at least there shouldn't be one.

I suggest two-step game "world display".
step 1: close-up display <-- what we already have.
step 2: when player flies high "towards the roof" (since there is no roof!) display should change to far-way view, showing much more, just like this:
https://youtu.be/ZZSwdqg6VE4?t=379 (watch about 10 seconds - world display changes)

**Comment by fallahn** [comment]
A test implementation is in bde44c43 . Zooming didn't work very well, although there is now technically infinite space above the player...
