### ISSUE TITLE
Immersion & UI improvement

### ISSUE THREAD

**Issue by gdinit** [fallahn/LunarMooner#12]
Suggestion 1:
High scores list start with zero entries thus a bad game makes it to the high scores list.
It should be pre-populated to 
1. prevent making it into the "high scores" with a low score
2. to make the game world appear more lively (people have been here, rather than clean slate)
3. perhaps to provide a motivation to play better - e.g. with realistic looking names (top 1 or 2 entries, challenging player to beat their near-unbeatable scores).

Suggestion 2: 
When player make it to the high scores, the form is too plain: "Enter your name: ___"
Perhaps it could be something like "CONGRATULATIONS! YOU HAVE THE 4TH HIGHEST SCORE" .
I'm not too sure about the 2nd sentence but the idea is give the feeling that player achieved something rather than plainly asking to fill in a  form :)

**Comment by fallahn** [comment]
Addressed in da246cc7 and 00a78640
