### ISSUE TITLE
Couple of notes with regards to gameflow control keys

### ISSUE THREAD

**Issue by gdinit** [fallahn/LunarMooner#8]
Enhancement request, couple of items:
1. While in game, ESC should bring up a menu with a button "EXIT TO MAIN MENU" and another one as "EXIT TO DESKTOP".
2. PauseBreak key does nothing. It should be bound to something. Either Pause/Resume or if there is no separate GamePaused state then at least bind it to "in-game menu" thus by pressing PauseBreak player can achieve the goal of stopping the game temporarily.

**Comment by fallahn** [comment]
Done. da246cc7
