### ISSUE TITLE
New Player Guidance

### ISSUE THREAD

**Issue by gdinit** [fallahn/LunarMooner#9]
Enhancement request: Upon launching the game for the first time ever, due to the name it is clear we are supposed to land on moon but other game elements are not very clear.

There needs to be some "play and discover" process I guess but without printing 500 page manual on screen we could still assist a new player with a tad bit nicely timed hints, such as:
1. Upon new round launch (when the 'mothership') is hovering left and right, perhaps display the message PRESS SPACE TO DETACH or something similar.
2. Maybe on Detach or on new round display a message that dudes below need help. Not to print multiple lines of text on screen perhaps it could be a thought bubble with S.O.S. or similar (image below). 

Dudes are literally dying there and I was enjoying the GUI (sorry but my first time in a space ship).
Make it obvious someone's going to die unless the player acts (and acts fast)!

[http://us.123rf.com/450wm/blankstock/blankstock1512/blankstock151200119/48925149-sos-lifebuoy-icon-heartbeat-cardiogram-symbol-swimming-sign-man-drowns-paper-speech-bubble-with-icon.jpg?ver=6](url)

**Comment by fallahn** [comment]
Implement now, to be fine tuned over time...
